openapi: 3.1.0
info:
  title: Media Storage API
  version: "1.0"
servers:
  - url: https://services.leadconnectorhq.com
components:
  securitySchemes: {}
paths:
  /medias/files:
    get:
      summary: Get list of files or folders
      description: >
        Requires the query param `type` with value `file` or `folder`.
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          example: Bearer <SEU_TOKEN>
        - in: header
          name: Version
          required: true
          schema:
            type: string
          example: "2021-04-15"
        - in: query
          name: type
          required: true
          schema:
            type: string
            enum:
              - file
              - folder
        - in: query
          name: altType
          required: false
          schema:
            type: string
          example: location
        - in: query
          name: altId
          required: false
          schema:
            type: string
          example: Xb9gDxwxYhdqtprGcb5E
        - in: query
          name: parentId
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
        "422":
          description: Missing or invalid type
